stages:
  - build
  - tests
  - publish_images

variables:
  POSTGRES_CONTAINER_VERSION: '0.4'
  POSTGRESQL_VERSION: '11'

#-----------------------------------------
# Build OCI image

build_image_pg:
  stage: build
  tags:
    - shell
  variables:
    BUILD_OPTS: '--network=internal_bridge --force-rm --no-cache'
  script:
    - docker build ${BUILD_OPTS} --force-rm -t article714/postgresql:${POSTGRESQL_VERSION}.${POSTGRES_CONTAINER_VERSION} --build-arg POSTGRES_CONTAINER_VERSION=10.${POSTGRES_CONTAINER_VERSION} .

#------------------------------------------
# QCheck (TODO)

#------------------------------------------
# Tests

test_image:
  stage: tests
  variables:
    POSTGRES_DB: pgtest
    POSTGRES_USER: a_tst_user
    POSTGRES_PASSWORD: a_tst_user
    POSTGRES_HOST_AUTH_METHOD: trust
  image:
    name: article714/postgresql:${POSTGRESQL_VERSION}.${POSTGRES_CONTAINER_VERSION}
  services:
    - name: article714/postgresql:${POSTGRESQL_VERSION}.${POSTGRES_CONTAINER_VERSION}
      alias: pg-srv
  tags:
    - docker
  script:
    - PGPASSWORD=a_tst_user psql -h pg-srv -U a_tst_user -w -l
