stages:
  - build
  - tests
  - publish_images

variables:
  POSTGRES_CERTIFICARE_VERSION: '10.0.1'
  DOCKER_REGISTRY_HOST: '83l02d2f.gra5.container-registry.ovh.net'

#-----------------------------------------
build_image:
  stage: build
  tags:
    - shell
  variables:
    BUILD_OPTS: '--force-rm --no-cache'
  script:
    - docker build ${BUILD_OPTS} --force-rm -t certificare/postgresql:${POSTGRES_CERTIFICARE_VERSION} -t ${DOCKER_REGISTRY_HOST}/certificare/postgresql:${POSTGRES_CERTIFICARE_VERSION} --build-arg POSTGRES_CERTIFICARE_VERSION=${POSTGRES_CERTIFICARE_VERSION} .

#------------------------------------------
# QCheck (TODO)

#------------------------------------------
# Tests

test_image:
  stage: tests
  image:
    name: certificare/postgresql:${POSTGRES_CERTIFICARE_VERSION}
  services:
    - name: certificare/postgresql:${POSTGRES_CERTIFICARE_VERSION}
      alias: pg-srv
  tags:
    - docker
  script:
    # wait for bindns to be fully fit
    - echo "TODO"

#------------------------------------------
# Publish
publish_image:
  stage: publish_images
  tags:
    - shell
  only:
    refs:
      - production
  script:
    - docker push ${DOCKER_REGISTRY_HOST}/certificare/postgresql:${POSTGRES_CERTIFICARE_VERSION}
