stages:
  - build
  - tests
  - publish_images

variables:
  POSTGRES_CONTAINER_VERSION: "0.2"

#-----------------------------------------
build_image_pg10:
  stage: build
  tags:
    - shell
  variables:
    BUILD_OPTS: "--force-rm --no-cache"
  script:
    - cp -a 10/Dockerfile .
    - docker build ${BUILD_OPTS} --force-rm -t article714/postgresql:10.${POSTGRES_CONTAINER_VERSION} --build-arg POSTGRES_CONTAINER_VERSION=10.${POSTGRES_CONTAINER_VERSION} .

#-----------------------------------------
build_image_pg11:
  stage: build
  tags:
    - shell
  variables:
    BUILD_OPTS: "--force-rm --no-cache"
  script:
    - cp -a 11/Dockerfile .
    - docker build ${BUILD_OPTS} --force-rm -t article714/postgresql:11.${POSTGRES_CONTAINER_VERSION} --build-arg POSTGRES_CONTAINER_VERSION=11.${POSTGRES_CONTAINER_VERSION} .

#------------------------------------------
# QCheck (TODO)

#------------------------------------------
# Tests

test_image_pg10:
  stage: tests
  variables:
    POSTGRES_DB: pgtest
    POSTGRES_USER: odoo
    POSTGRES_PASSWORD: odoo
    POSTGRES_HOST_AUTH_METHOD: trust
  image:
    name: article714/postgresql:10.${POSTGRES_CONTAINER_VERSION}
  services:
    - name: article714/postgresql:10.${POSTGRES_CONTAINER_VERSION}
      alias: pg-srv
  tags:
    - docker
  script:
    - PGPASSWORD=odoo psql -h pg-srv -u odoo -w -l

test_image_pg11:
  stage: tests
  variables:
    POSTGRES_DB: pgtest
    POSTGRES_USER: odoo
    POSTGRES_PASSWORD: odoo
    POSTGRES_HOST_AUTH_METHOD: trust
  image:
    name: article714/postgresql:11.${POSTGRES_CONTAINER_VERSION}
  services:
    - name: article714/postgresql:11.${POSTGRES_CONTAINER_VERSION}
      alias: pg-srv
  tags:
    - docker
  script:
    - PGPASSWORD=odoo psql -h pg-srv -u odoo -l
