language: python
sudo: false
cache: pip

services:
  - docker

script:
  - export BUILD_OPTS='--force-rm --no-cache'
  - export POSTGRESQL_CONTAINER_VERSION='0.2'
  - docker build ${BUILD_OPTS} -t article714/postgresql:travis-${POSTGRESQL_CONTAINER_VERSION} --build-arg POSTGRESQL_CONTAINER_VERSION=10.${POSTGRESQL_CONTAINER_VERSION} .
