language: python
sudo: false
cache: pip

services:
  - docker

script:
  - export BUILD_OPTS='--force-rm --no-cache'
  - export POSTGRESQL_CONTAINER_VERSION='0.1'
  - docker build ${BUILD_OPTS} -t article714/postgresql:10.${POSTGRESQL_CONTAINER_VERSION} --build-arg POSTGRESQL_CONTAINER_VERSION=10.${POSTGRESQL_CONTAINER_VERSION} 10
  - docker build ${BUILD_OPTS} -t article714/postgresql:11.${POSTGRESQL_CONTAINER_VERSION} --build-arg POSTGRESQL_CONTAINER_VERSION=11.${POSTGRESQL_CONTAINER_VERSION} 11
